apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-aws-ec2-actions-runners
  namespace: tx-pts-dai
  description: terraform-aws-ec2-actions-runners component
  annotations:
    github.com/project-slug: tx-pts-dai/terraform-aws-ec2-actions-runners
  tags:
    - tx-pts-dai
spec:
  type: infrastructure
  lifecycle: production
  owner: group:default/dai